name: Python Syntax Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install flake8
      run: |
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        # Run flake8 on all .py files in the repository
        find . -name "*.py" | xargs flake8
